server {
    listen 443 ssl;
    listen [::]:443 ssl;
    ssl_certificate /etc/letsencrypt/live/freeinvoices.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/freeinvoices.xyz/privkey.pem;
    server_name freeinvoices.xyz;
    root /home/francip/src/freeinvoices/dist;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
}
